### ISSUE TITLE
[MNT] Requirements and version pins

### ISSUE THREAD

**Issue by mscheltienne** [MIPLabCH/nigsp#40]
Hello,

Looking a bit into the requirements to prepare for a conda recipe, and I have a couple of questions:

**Numpy**
- `requirements.txt` only list `numpy>=1.9.3` and is not used anywhere
- `setup.cfg` list a different version of numpy: https://github.com/MIPLabCH/nigsp/blob/f128a7c2a31f5bcc49d68dfae4ca2c8eea6bde24/setup.cfg#L27-L29

Can we remove `requirements.txt`? Any reason for the pin of the numpy version?

**Python**
Python version is set to https://github.com/MIPLabCH/nigsp/blob/f128a7c2a31f5bcc49d68dfae4ca2c8eea6bde24/setup.cfg#L26

With the rule of 4 minor version supported and the recent release of Python 3.11, most packages are moving towards Python 3.8 and above. IIRC conda is in the process of dropping support for Python 3.7. Do you mind to bump the requirement to 3.8? Or at least 3.7?

**Viz**
Matplotlib and Nilearn are pinned to https://github.com/MIPLabCH/nigsp/blob/f128a7c2a31f5bcc49d68dfae4ca2c8eea6bde24/setup.cfg#L43-L45

Any reason? Especially for the matplotlib pin?

**Style**
Looking at the pin for `black` and `isort`: https://github.com/MIPLabCH/nigsp/blob/f128a7c2a31f5bcc49d68dfae4ca2c8eea6bde24/setup.cfg#L55-L59
Those versions don't exist yet.

**Comment by smoia** [comment]
:rocket: Issue was released in [`0.12.1`](https://github.com/MIPLabCH/nigsp/releases/tag/0.12.1) :rocket:
